baseURL = "https://nikolaosbakogiannis.com/"
languageCode = "en-us"
theme = "aafu"

[params]
author = "Nikolaos Bakogiannis"
copyright = "this webspace is based on aafu theme for hugo"
description = "Nikolaos Bakogiannis site"
title = "nikolaosbakogiannisWebsite"

[params.theme]
# Available themes are 'light', 'dark', 'ocean', and 'pinkish'
mainTheme = "dark"
# setting false below will hide 'aafu by darshan' displayed under the profile pic
showAttribute = true
singlePage = false

[params.favicons]
metas = '''
        <link rel="apple-touch-icon" sizes="180x180" href="apple-touch-icon.png">
        <link rel="icon" type="image/png" sizes="32x32" href="favicon-32x32.png">
        <link rel="icon" type="image/png" sizes="16x16" href="favicon-16x16.png">
        <link rel="manifest" href="site.webmanifest">
        <link rel="mask-icon" href="safari-pinned-tab.svg" color="#252627">
        <link rel="shortcut icon" href="favicon.ico">
        '''
use = true

# Profile section
[params.profile]
location = "Zurich, CH"
name = "Nikolaos Bakogiannis"
photo = "bako_profile.jpg"
tagline = ""

# Section for links to social websites
[params.social]
title = "Links"


[[params.social.list]]
icon = "fab fa-stack-overflow"
title = "StackOverflow"
url = "https://stackoverflow.com/users/12337730/kimbogilda"
[[params.social.list]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/KimboGilda"
# [[params.social.list]]
# icon = "fab fa-orcid"
# title = "Orcid"
# url = "#"
# [[params.social.list]]
# icon = "ai ai-google-scholar"
# title = "Google Scholar"
# url = "#"
# [[params.social.list]]
# icon = "fab fa-researchgate"
# title = "ResearchGate"
# url = "#"

#Specify what is showin in the Accordion
[[params.showInAccordion]]
expand = true # true for the section that is initially expanded
item = "aboutme" 
[[params.showInAccordion]]
item = "experience"
[[params.showInAccordion]]
item = "education"
[[params.showInAccordion]]
item = "publication"
[[params.showInAccordion]]
item = "project"
[[params.showInAccordion]]
item = "skill"
[[params.showInAccordion]]
item = "hobby"

[params.aboutme]
description = "My name is Nikolaos Bakogiannis."
icon = "fas fa-user"
title = "About Me"

# Experience section
[params.experience]
icon = "fas fa-briefcase"
title = "Experience"

[[params.experience.list]]
company = "Zurich University of Applied Sciences (ZHAW)"
dates = "2019 - *Present*"
details = ""
position = "Scientific Assistant in Geoinformatic Research Group"
[[params.experience.list]]
company = "Leica Geosystems AG"
dates = "2018 - 2019"
position = "Intern in Computer Vision Department"
url = "#"

# Education section
[params.education]
icon = "fas fa-graduation-cap"
title = "Education"

[[params.education.list]]
college = "Swiss Federal Institute of Technology in Zurich (ETH Zürich)"
dates = "2016-2018"
degree = "MSc in Geomatic Engineering"
thesis_title = "Cartographic visualization for indoor semantic wayfinding"
thesis_url = "https://karto.ethz.ch/studium/studentenarbeiten/master/master.html"
[[params.education.list]]
college = "Athens University of Economics and Business (AUEB)"
dates = "2012 - 2014"
degree = "Master in Business Administration (MBA)"
thesis_title = ""
thesis_url = "#"
[[params.education.list]]
college = "National Technical University of Athens (NTUA), School of Rural and Surveying Engineering (SRSE)"
dates = "2005 - 2010"
degree = "Master in Rural and Surveying Engineering"

# Publication section
[params.publication]
icon = "fas fa-book"
title = "Publications"
#The order below determines the order in which the items appear in "Publications" section
format = ["date", "authors", "title", "journal"]
#If you don't want to group publications, comment the line below by adding # at the beginning
types = ["Journal Articles", "Proceedings"]

[[params.publication.list]]
authors = "Göbel, F., Bakogiannis, N., Henggeler, K., Tschümperlin, R., Xu, Y., Kiefer, P. and Raubal, M"
date = "2018, January"
journal = "In Eye Tracking for Spatial Research"
title = "A Public Gaze-Controlled Campus Map. 3rd International Workshop. ETH Zurich"
type = "Proceedings"
url = "https://www.research-collection.ethz.ch/handle/20.500.11850/222491"

[[params.publication.list]]
authors = "Bakogiannis, N., Gkonos, C. and Hurni, L."
date = "2019"
journal = "Multimodal Technologies and Interaction, 3(1), p.22."
title = "Cartographic Visualization for Indoor Semantic Wayfinding."
type = "Journal Articles"
url = "https://www.mdpi.com/2414-4088/3/1/22"

# Project section
[params.project]
icon = "fas fa-project-diagram"
title = "Project"

[[params.project.list]]
description = "Project member" 
title = "Prävention von Wildtierunfällen auf Verkehrsinfrastrukturen"
url = "https://www.zhaw.ch/de/lsfm/institute-zentren/iunr/ecosystems-and-biodiversity/geoinformatik/referenzprojekte/praevention-von-wildtierunfaellen-auf-verkehrsinfrastrukturen/"
[[params.project.list]]
description = "Description of the project"
title = "Project 2"
url = "#"
[[params.project.list]]
description = "Description of the project"
title = "Project 3"
url = "#"
[[params.project.list]]
description = "Description of the project"
title = "Project 4"
url = "#"

# Skill section
[params.skill]
icon = "fas fa-cogs"
panelId = "skill-panel"
title = "Skill"

[[params.skill.list]]
skill = "GIS"
skillrating = 100
[[params.skill.list]]
skill = "R"
skillrating = 70
[[params.skill.list]]
skill = "Python"
skillrating = 70

[[params.skill.list]]
skill = "Machine learning"
skillrating = 20

# Hobby section
[params.hobby]
icon = "fas fa-gamepad"
title = "Hobby"

[[params.hobby.list]]
hobby = "Cooking"
[[params.hobby.list]]
hobby = "Playing ukulele"
[[params.hobby.list]]
hobby = "Trying to remember how I used to play football"
