baseURL = "https://nikolaosbakogiannis.com/"
languageCode = "en-us"
theme = "aafu"

[params]
author = "Nikolaos Bakogiannis"
copyright = "short copyright message"
description = "Nikolaos Bakogiannis site"
title = "My site"

[params.theme]
# Available themes are 'light', 'dark', 'ocean', and 'pinkish'
mainTheme = "dark"
# setting false below will hide 'aafu by darshan' displayed under the profile pic
showAttribute = false
singlePage = false

[params.favicons]
metas = '''
        <link rel="apple-touch-icon" sizes="180x180" href="apple-touch-icon.png">
        <link rel="icon" type="image/png" sizes="32x32" href="favicon-32x32.png">
        <link rel="icon" type="image/png" sizes="16x16" href="favicon-16x16.png">
        <link rel="manifest" href="site.webmanifest">
        <link rel="mask-icon" href="safari-pinned-tab.svg" color="#252627">
        <link rel="shortcut icon" href="favicon.ico">
        '''
use = true

# Profile section
[params.profile]
location = "Zurich, CH"
name = "Nikolaos Bakogiannis, Bako"
photo = "bako_profile.jpg"
tagline = ""

# Section for links to social websites
[params.social]
title = "Links"


[[params.social.list]]
icon = "fab fa-stack-overflow"
title = "StackOverflow"
url = "#"
[[params.social.list]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/KimboGilda"
[[params.social.list]]
icon = "fab fa-orcid"
title = "Orcid"
url = "#"
[[params.social.list]]
icon = "ai ai-google-scholar"
title = "Google Scholar"
url = "#"
[[params.social.list]]
icon = "fab fa-researchgate"
title = "ResearchGate"
url = "#"

#Specify what is showin in the Accordion
[[params.showInAccordion]]
expand = true # true for the section that is initially expanded
item = "aboutme" 
[[params.showInAccordion]]
item = "experience"
[[params.showInAccordion]]
item = "education"
[[params.showInAccordion]]
item = "publication"
[[params.showInAccordion]]
item = "project"
[[params.showInAccordion]]
item = "skill"
[[params.showInAccordion]]
item = "hobby"

[params.aboutme]
description = "My name is Nikolaos (Nikos) Bakogiannis. I really love working with geospatial data and "
icon = "fas fa-user"
title = "About Me"

# Experience section
[params.experience]
icon = "fas fa-briefcase"
title = "Experience"

[[params.experience.list]]
company = "Company Name"
dates = "2019 - *Present*"
details = "Printed from desktop. Sent [emails](#). Called people using telephone. Drank water from office cooler. Ate donuts on people's birthdays."
position = "Job Title"
[[params.experience.list]]
company = "Company Name"
dates = "2018 - 2019"
position = "Job Title"
url = "#"

# Education section
[params.education]
icon = "fas fa-graduation-cap"
title = "Education"

[[params.education.list]]
college = "Swiss Federal Institute of Technology in Zurich (ETH)"
dates = "2016-2018"
degree = "MSc in Geomatics"
thesis_title = "Semantiv"
thesis_url = "#"
[[params.education.list]]
college = "Athens University of Economics and Business (AUEB)"
dates = "2012 - 2014"
degree = "Master in Business Administration (MBA)"
thesis_title = ""
thesis_url = "#"
[[params.education.list]]
college = "National Technical University of Athens (NTUA)"
dates = "2005 - 2010"
degree = "Master in Rural and Surveying Engineering"

# Publication section
[params.publication]
icon = "fas fa-book"
title = "Publications"
#The order below determines the order in which the items appear in "Publications" section
format = ["date", "authors", "title", "journal"]
#If you don't want to group publications, comment the line below by adding # at the beginning
types = ["Journal Articles", "Proceedings"]

[[params.publication.list]]
authors = "F Last, F Second, P secondary"
date = "2018"
journal = "Journal of Field 52 (16), 9033-9044"
title = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
type = "Journal Articles"
url = "#"

[[params.publication.list]]

authors = "F Last, F Second, P secondary"
date = "2018"
journal = "Journal of Field 52 (16), 9033-9044"
title = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
type = "Journal Articles"
url = "#"
[[params.publication.list]]
authors = "F Last, F Second, P secondary"
date = "2018"
journal = "Journal of Field 52 (16), 9033-9044"
title = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
type = "Proceedings"
url = "#"

# Project section
[params.project]
icon = "fas fa-project-diagram"
title = "Project"

[[params.project.list]]
description = "Description of the project"
title = "Project 1"
url = "#"
[[params.project.list]]
description = "Description of the project"
title = "Project 2"
url = "#"
[[params.project.list]]
description = "Description of the project"
title = "Project 3"
url = "#"
[[params.project.list]]
description = "Description of the project"
title = "Project 4"
url = "#"

# Skill section
[params.skill]
icon = "fas fa-cogs"
panelId = "skill-panel"
title = "Skill"

[[params.skill.list]]
skill = "GIS"
skillrating = 100
[[params.skill.list]]
skill = "R"
skillrating = 70
[[params.skill.list]]
skill = "Python"
skillrating = 70

[[params.skill.list]]
skill = "Machine learning"
skillrating = 20

# Hobby section
[params.hobby]
icon = "fas fa-gamepad"
title = "Hobby"

[[params.hobby.list]]
hobby = "Cooking"
[[params.hobby.list]]
hobby = "Playing ukulele"
[[params.hobby.list]]
hobby = "Trying to remember how I used to play football"
